DROP TABLE IF EXISTS pies;

CREATE TABLE pies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  whole_pie BOOL NOT NULL,
  slice BOOL NOT NULL,
  slice_quantity INTEGER NOT NULL,
  gif TEXT NOT NULL
);