DROP TABLE IF EXISTS pies

CREATE TABLE pies (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  full_pie BOOL NOT NULL,
  slice BOOL NOT NULL,
  slice_quantity INTEGER NOT NULL
)